# Generated by Django 3.0.8 on 2020-07-28 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200725_0331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='date',
            field=models.DateField(help_text='Enter dd/mm/yyyy Formate Date'),
        ),
    ]
