# Generated by Django 3.0.8 on 2020-08-08 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200808_1157'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Card',
        ),
    ]
