# Generated by Django 3.0.8 on 2020-08-08 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_delete_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image_name', models.ImageField(upload_to='polls/static/images')),
                ('type', models.CharField(max_length=50)),
            ],
        ),
    ]
